---
database:
  # A valid DSN for Postgres https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL
  dsn: "host=localhost user=launchbox password=password dbname=launchbox port=5432 sslmode=disable"

redis:
  url: ""
  password: ""

centrifugo:
  enabled: true
  # URL for connecting to Centrifugo https://centrifugal.dev/docs/server/configuration#default-endpoints
  url: "ws://localhost:8000/connection/websocket"

prometheus:
  enabled: true
  url: ""

loki:
  enabled: true
  url: ""

vault:
  enabled: true
  url: ""

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - "*"
  allowed_headers:
    - Origin
    - Content-Type
  expose_headers:
    - Content-Length
  allow_credentials: true
  # 12 hours
  max_age: 43200

port: 8080

