---
development:
  dialect: postgres
  database: launchbox_development
  user: launchbox
  password: password
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://launchbox:password@127.0.0.1:5432/launchbox_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/launchbox_production?sslmode=disable"}}
