# permissions for end users to view revisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: revision-viewer-role
rules:
- apiGroups:
  - launchbox.io
  resources:
  - revisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - launchbox.io
  resources:
  - revisions/status
  verbs:
  - get
