package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"launchbox/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (AccessToken)
// DB Table: Plural (access_tokens)
// Resource: Plural (AccessTokens)
// Path: Plural (/access_tokens)
// View Template Folder: Plural (/templates/access_tokens/)

// AccessTokensResource is the resource for the AccessToken model
type AccessTokensResource struct {
	buffalo.Resource
}

// List gets all AccessTokens. This function is mapped to the path
// GET /access_tokens
func (v AccessTokensResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	accessTokens := &models.AccessTokens{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all AccessTokens from the DB
	if err := q.All(accessTokens); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("accessTokens", accessTokens)
		return c.Render(http.StatusOK, r.HTML("access_tokens/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(accessTokens))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(accessTokens))
	}).Respond(c)
}

// Show gets the data for one AccessToken. This function is mapped to
// the path GET /access_tokens/{access_token_id}
func (v AccessTokensResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty AccessToken
	accessToken := &models.AccessToken{}

	// To find the AccessToken the parameter access_token_id is used.
	if err := tx.Find(accessToken, c.Param("access_token_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("accessToken", accessToken)

		return c.Render(http.StatusOK, r.HTML("access_tokens/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(accessToken))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(accessToken))
	}).Respond(c)
}

// New renders the form for creating a new AccessToken.
// This function is mapped to the path GET /access_tokens/new
func (v AccessTokensResource) New(c buffalo.Context) error {
	c.Set("accessToken", &models.AccessToken{})

	return c.Render(http.StatusOK, r.HTML("access_tokens/new.plush.html"))
}

// Create adds a AccessToken to the DB. This function is mapped to the
// path POST /access_tokens
func (v AccessTokensResource) Create(c buffalo.Context) error {
	// Allocate an empty AccessToken
	accessToken := &models.AccessToken{}

	// Bind accessToken to the html form elements
	if err := c.Bind(accessToken); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(accessToken)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("accessToken", accessToken)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("access_tokens/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "accessToken.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/access_tokens/%v", accessToken.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(accessToken))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(accessToken))
	}).Respond(c)
}

// Edit renders a edit form for a AccessToken. This function is
// mapped to the path GET /access_tokens/{access_token_id}/edit
func (v AccessTokensResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty AccessToken
	accessToken := &models.AccessToken{}

	if err := tx.Find(accessToken, c.Param("access_token_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("accessToken", accessToken)
	return c.Render(http.StatusOK, r.HTML("access_tokens/edit.plush.html"))
}

// Update changes a AccessToken in the DB. This function is mapped to
// the path PUT /access_tokens/{access_token_id}
func (v AccessTokensResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty AccessToken
	accessToken := &models.AccessToken{}

	if err := tx.Find(accessToken, c.Param("access_token_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind AccessToken to the html form elements
	if err := c.Bind(accessToken); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(accessToken)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("accessToken", accessToken)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("access_tokens/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "accessToken.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/access_tokens/%v", accessToken.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(accessToken))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(accessToken))
	}).Respond(c)
}

// Destroy deletes a AccessToken from the DB. This function is mapped
// to the path DELETE /access_tokens/{access_token_id}
func (v AccessTokensResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty AccessToken
	accessToken := &models.AccessToken{}

	// To find the AccessToken the parameter access_token_id is used.
	if err := tx.Find(accessToken, c.Param("access_token_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(accessToken); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "accessToken.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/access_tokens")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(accessToken))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(accessToken))
	}).Respond(c)
}
