package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"launchbox/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Revision)
// DB Table: Plural (revisions)
// Resource: Plural (Revisions)
// Path: Plural (/revisions)
// View Template Folder: Plural (/templates/revisions/)

// RevisionsResource is the resource for the Revision model
type RevisionsResource struct {
	buffalo.Resource
}

// List gets all Revisions. This function is mapped to the path
// GET /revisions
func (v RevisionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	revisions := &models.Revisions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Revisions from the DB
	if err := q.All(revisions); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("revisions", revisions)
		return c.Render(http.StatusOK, r.HTML("revisions/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(revisions))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(revisions))
	}).Respond(c)
}

// Show gets the data for one Revision. This function is mapped to
// the path GET /revisions/{revision_id}
func (v RevisionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Revision
	revision := &models.Revision{}

	// To find the Revision the parameter revision_id is used.
	if err := tx.Find(revision, c.Param("revision_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("revision", revision)

		return c.Render(http.StatusOK, r.HTML("revisions/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(revision))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(revision))
	}).Respond(c)
}

// New renders the form for creating a new Revision.
// This function is mapped to the path GET /revisions/new
func (v RevisionsResource) New(c buffalo.Context) error {
	c.Set("revision", &models.Revision{})

	return c.Render(http.StatusOK, r.HTML("revisions/new.plush.html"))
}

// Create adds a Revision to the DB. This function is mapped to the
// path POST /revisions
func (v RevisionsResource) Create(c buffalo.Context) error {
	// Allocate an empty Revision
	revision := &models.Revision{}

	// Bind revision to the html form elements
	if err := c.Bind(revision); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(revision)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("revision", revision)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("revisions/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "revision.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/revisions/%v", revision.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(revision))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(revision))
	}).Respond(c)
}

// Edit renders a edit form for a Revision. This function is
// mapped to the path GET /revisions/{revision_id}/edit
func (v RevisionsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Revision
	revision := &models.Revision{}

	if err := tx.Find(revision, c.Param("revision_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("revision", revision)
	return c.Render(http.StatusOK, r.HTML("revisions/edit.plush.html"))
}

// Update changes a Revision in the DB. This function is mapped to
// the path PUT /revisions/{revision_id}
func (v RevisionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Revision
	revision := &models.Revision{}

	if err := tx.Find(revision, c.Param("revision_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Revision to the html form elements
	if err := c.Bind(revision); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(revision)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("revision", revision)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("revisions/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "revision.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/revisions/%v", revision.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(revision))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(revision))
	}).Respond(c)
}

// Destroy deletes a Revision from the DB. This function is mapped
// to the path DELETE /revisions/{revision_id}
func (v RevisionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Revision
	revision := &models.Revision{}

	// To find the Revision the parameter revision_id is used.
	if err := tx.Find(revision, c.Param("revision_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(revision); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "revision.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/revisions")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(revision))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(revision))
	}).Respond(c)
}
