package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"launchbox/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Secret)
// DB Table: Plural (secrets)
// Resource: Plural (Secrets)
// Path: Plural (/secrets)
// View Template Folder: Plural (/templates/secrets/)

// SecretsResource is the resource for the Secret model
type SecretsResource struct {
	buffalo.Resource
}

// List gets all Secrets. This function is mapped to the path
// GET /secrets
func (v SecretsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	secrets := &models.Secrets{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Secrets from the DB
	if err := q.All(secrets); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("secrets", secrets)
		return c.Render(http.StatusOK, r.HTML("secrets/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(secrets))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(secrets))
	}).Respond(c)
}

// Show gets the data for one Secret. This function is mapped to
// the path GET /secrets/{secret_id}
func (v SecretsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Secret
	secret := &models.Secret{}

	// To find the Secret the parameter secret_id is used.
	if err := tx.Find(secret, c.Param("secret_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("secret", secret)

		return c.Render(http.StatusOK, r.HTML("secrets/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(secret))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(secret))
	}).Respond(c)
}

// New renders the form for creating a new Secret.
// This function is mapped to the path GET /secrets/new
func (v SecretsResource) New(c buffalo.Context) error {
	c.Set("secret", &models.Secret{})

	return c.Render(http.StatusOK, r.HTML("secrets/new.plush.html"))
}

// Create adds a Secret to the DB. This function is mapped to the
// path POST /secrets
func (v SecretsResource) Create(c buffalo.Context) error {
	// Allocate an empty Secret
	secret := &models.Secret{}

	// Bind secret to the html form elements
	if err := c.Bind(secret); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(secret)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("secret", secret)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("secrets/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "secret.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/secrets/%v", secret.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(secret))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(secret))
	}).Respond(c)
}

// Edit renders a edit form for a Secret. This function is
// mapped to the path GET /secrets/{secret_id}/edit
func (v SecretsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Secret
	secret := &models.Secret{}

	if err := tx.Find(secret, c.Param("secret_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("secret", secret)
	return c.Render(http.StatusOK, r.HTML("secrets/edit.plush.html"))
}

// Update changes a Secret in the DB. This function is mapped to
// the path PUT /secrets/{secret_id}
func (v SecretsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Secret
	secret := &models.Secret{}

	if err := tx.Find(secret, c.Param("secret_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Secret to the html form elements
	if err := c.Bind(secret); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(secret)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("secret", secret)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("secrets/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "secret.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/secrets/%v", secret.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(secret))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(secret))
	}).Respond(c)
}

// Destroy deletes a Secret from the DB. This function is mapped
// to the path DELETE /secrets/{secret_id}
func (v SecretsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Secret
	secret := &models.Secret{}

	// To find the Secret the parameter secret_id is used.
	if err := tx.Find(secret, c.Param("secret_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(secret); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "secret.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/secrets")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(secret))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(secret))
	}).Respond(c)
}
