

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Syntax
        run: |
          formatted_count=$(gofmt -s -l . | wc -l)
          if [ "${formatted_count}" -ne 0 ] ; then
            echo "Run 'go fmt github.com/robwittman/launchbox...'"
            exit 1
          fi
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...